apiVersion: v1
kind: Service
metadata:
  name: roman-numerals-server
  labels:
    name: roman-numerals-service
    app: roman-numerals-app
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
  #type: LoadBalancer
  selector:
     name: roman-numerals-pod
     app: roman-numerals-app