apiVersion: v1
kind: Service
metadata:
  name: webapp-delayed-service
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: {{ .Values.webapp_service.port }}
  selector:
     app: webapp-delayed
  type: {{ .Values.webapp_service.type }}