apiVersion: v1
kind: Service
metadata:
  name: {{ include "kittens-chart.fullname" . }}
  labels:
    {{- include "kittens-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.port }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kittens-chart.selectorLabels" . | nindent 4 }}
