# Default values for webapp-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

webapp_deployment_image: aydintokuslu/simple-mysql:4.0
mysql_deployment_image: mysql:5.7


mysql_service:
  type: ClusterIP
  port: 3306

webapp_service:
  type: NodePort
  port: 30005

