apiVersion: v1
kind: Service
metadata:
  name: bookstore-api-server
  labels:
    name: bookstore-api-service
    app: bookstore-api-app
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ .Values.bookstore_service.port }}
  type: {{ .Values.bookstore_service.type }}
  selector:
     name: bookstore-api-pod
     app: bookstore-api-app