apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.webapp_deployment_image }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-secret-volumes
          mountPath: "/opt/app-secret-volumes"
          readOnly: true
        envFrom:
          - secretRef:
              name: app-secret
      volumes:
        - name: app-secret-volumes
          secret:
            secretName: app-secret